name: Build Autotrain Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-autotrain-docker.yml
      - autotrain/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force

      - name: Download data splits
        run: |
          python scripts/download_data.py

      - name: Build Docker image
        run: |
          docker build -f autotrain/Dockerfile -t autotrain:latest .
          docker save autotrain:latest -o autotrain-docker.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: autotrain-docker
          path: autotrain-docker.tar
          if-no-files-found: error
